### ISSUE TITLE
[LAMBDA] GET요청 파라미터 처리

### ISSUE THREAD

**Issue by boribap** [seed-kau/Todays-Movie#11]
요청으로 주는 파라미터가 lambda로 넘어가지 않아 이슈 생김

**Comment by boribap** [comment]
1. Use Lambda Proxy integration 를 사용 -> 해결

[https://stackoverflow.com/questions/31329958/how-to-pass-a-querystring-or-route-parameter-to-aws-lambda-from-amazon-api-gatew](https://stackoverflow.com/questions/31329958/how-to-pass-a-querystring-or-route-parameter-to-aws-lambda-from-amazon-api-gatew)


2. Malformed Lambda proxy response 문제 생김 -> api gateway가 원하는 응답형식이 아니라 생김 -> 해결 

[https://stackoverflow.com/questions/43708017/aws-lambda-api-gateway-error-malformed-lambda-proxy-response](https://stackoverflow.com/questions/43708017/aws-lambda-api-gateway-error-malformed-lambda-proxy-response)

**Comment by Danpatpang** [comment]
👍
