### ISSUE TITLE
[MH] API 생성 및 JSON 통신

### ISSUE THREAD

**Issue by Danpatpang** [seed-kau/Todays-Movie#2]
AWS Mobile Hub에서 API Gateway 생성 및 Lambda를 API Gateway에 연결.
사용자의 경우 API Key 값을 통해 Lambda로 접근.

![image](https://user-images.githubusercontent.com/19412222/56263595-83d1f900-611e-11e9-97ce-af20a780e31e.png)

**Comment by Danpatpang** [comment]
API Gateway 생성 시 private, protected, public 선택해야 함.
(테스트는 public으로 진행.)
![image](https://user-images.githubusercontent.com/19412222/56413319-13fc7380-62c2-11e9-9e6f-cbfaf65ff251.png)

**Comment by Danpatpang** [comment]
Mobile Hub에서 생성하는 리소스는 브라우저에서 접근이 가능하지만,
Lambda Trigger를 통해 직접 생성하는 리소스의 경우 다음과 같은 에러를 출력.

`{"message":"Missing Authentication Token"}`

> 보안을 open을 하든, API 필요를 하든 결과는 동일

**Comment by boribap** [comment]
에러가 나는 이유 확인 및 수정

1. 각 메소드마다 응답 메소드 추가 + 응답 스키마 설정해야함 
2. 사용량계획에 올바른 스테이지 추가

**Comment by Danpatpang** [comment]
Postman에서 API 키를 통한 Lambda 접근 확인. (GET / POST)
![image](https://user-images.githubusercontent.com/19412222/56460114-70ea4d80-63d8-11e9-8db7-72a15cdd398a.png)
