### ISSUE TITLE
[LEX] Lambda에서 Lex 호출 및 통신

### ISSUE THREAD

**Issue by Danpatpang** [seed-kau/Todays-Movie#5]

**Comment by Danpatpang** [comment]
- [ ] 현재 Google Translate API가 연결되었으므로 한글 데이터 셋을 영어 데이터 셋으로 변경 필요.

- [ ] Lex를 호출하기 전 예제 데이터 셋으로 Lex를 구축해야 함.

- [ ] 구축된 Lex를 API Gateway와 Lambda를 이용해서 연동할 것.

**Comment by Danpatpang** [comment]
외부 API키를 Secrets Manager에서 관리할 때 통신 시 생각보다 많은 시간이 소요된다.
1. Google Translation API : 0.8s
2. Papago API : 1.6s
3. Google Translation API + Secrets Manager + Lex : 4.6s

즉, 요청에 대한 응답 시간은 약 6 ~ 8초 정도 소요될 것으로 예상된다.
좀 더 응답을 빠르게 하기위해 방법을 찾아봐야 한다.

**Comment by Danpatpang** [comment]
테스트 통신 성공.
url 접근 시 AWS API gateway에서 발급받은 API key 값을 이용하여 접근한다.

보내는 내용 : "한글 메시지"
받는 내용 : "lex의 영어 응답"

![image](https://user-images.githubusercontent.com/19412222/56897779-5ac04980-6aca-11e9-9468-f40d3059768f.png)

**Comment by boribap** [comment]
테스트 통신 성공.

보내는 내용 : "한글 메세지"
받는 내용 : "lex의 영어 응답 번역 결과"

![image](https://user-images.githubusercontent.com/28684368/56971580-73049700-6ba4-11e9-80b0-36efe1b22225.png)
